--1 DB
--CREATE DATABASE JobsBG;
--USE JobsBG;
--GO


CREATE TABLE Employer(
email NVARCHAR(20)NOT NULL PRIMARY KEY,
CompanyPassword NVARCHAR(20) NOT NULL,
CompanyName NVARCHAR(40) NOT NULL,
CompanyAddress NVARCHAR(50)NOT NULL,
EIK NVARCHAR(20)NOT NULL,
Sector NVARCHAR(20) NOT NULL,
CompanySite NVARCHAR(50) NOT NULL,
History NVARCHAR(300),
);

CREATE TABLE AdvertisementM(
advTitle NVARCHAR(40) NOT NULL,
advSalary NVARCHAR(5),
advPosition NVARCHAR(40),
advTown NVARCHAR(20),
advert NVARCHAR (4000) NOT NULL,
advBusyness NVARCHAR(20),
advLevel NVARCHAR(20) NOT NULL,
email NVARCHAR(40),
IsApproved NVARCHAR (3) NOT NULL,
);

CREATE TABLE Administrator(
emailAdmin NVARCHAR(20)NOT NULL PRIMARY KEY,
AdminPassword NVARCHAR(20) NOT NULL,
SecretCode NVARCHAR(10),
);


CREATE TABLE Employee(
e_mail NVARCHAR(40) NOT NULL PRIMARY KEY,
name NVARCHAR(40) NOT NULL,
UserPassword NVARCHAR(40) NOT NULL,
HighSchool NVARCHAR(40) NOT NULL,
University NVARCHAR(40) NOT NULL,
PreviousWork1 NVARCHAR(40),
PreviousWork2 NVARCHAR(40),
PreviousWork3 NVARCHAR(40),
ForeignLanguage NVARCHAR(20),
Age NVARCHAR(2) NOT NULL,
UserAddress NVARCHAR (40) NOT NULL,
WhyQuestion NVARCHAR (50),
);

